name: snakemake-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=7.3
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.19
  - pygments
  - python==3.10.12
  - inmoose
  - bioinfokit==2.1.2
  - R =4.2.2
  - argparse =2.2.2
  - preprocessCore =1.61.1
  - limma =3.56.2
  - edgeR =3.42.4
  - RUVSeq
